### ISSUE TITLE
[Garf\LaravelConf\Contracts\Factory] is not instantiable

### ISSUE THREAD

**Issue by Khalilbz** [gaaarfild/laravel-conf#11]
It didn't work for me, at all, after a lot of issues I found this solution, I don't know how it worked but I got the idea from the other laravel Facade config files like "view" .

**Solution:**
in [_/vendor/garf/laravel-conf/src/ConfFacade.php_]
change this line :
`return \Garf\LaravelConf\Contracts\Factory::class;`
to this :
`return "conf";`

I don't know if this is the best solution.

**Comment by garf** [comment]
Hi Khalil,
Thank you for reporting the issue. 
Which version of Laravel you are using?

**Comment by Khalilbz** [comment]
Sorry sir, I made a mistake, this error happened because I was calling the configs like this:
`Conf::all();`
not like this:
`conf()->all();`
And the solution made the first one run correctly.

---------------------------------------

> **I'm using :**
>         **php**: "7.0"
>         **garf/laravel-conf**: "3.\*"
>         **laravel**: "5.6.\*"
