### ISSUE TITLE
Possibility of adding custom filepath

### ISSUE THREAD

**Issue by axelex** [gaaarfild/laravel-conf#4]
Can you please replace your constructor with this:

``` php
    public function __construct($filepath)
    {
        $this->file = ($filepath) ? $filepath : storage_path('app/conf.json');
        if (empty($this->config)) {
            if (!file_exists($this->file)) {
                file_put_contents($this->file, json_encode([]));
            }
            $this->config = collect(json_decode(file_get_contents($this->file), true));
        }
    }

```

or other change so the config path to be customizable?

**Comment by garf** [comment]
Please, make Pull Request with your changes.
We will review the changes and accept them.

**Comment by axelex** [comment]
I'll try... I haven't made a pull request before.

**Comment by garf** [comment]
Good chance to try ;)

**Comment by axelex** [comment]
When I try to commit my changes I get:
remote: Permission to gaaarfild/laravel-conf.git denied to axelex.
fatal: unable to access 'https://github.com/gaaarfild/laravel-conf.git/': The requested URL returned error: 403

**Comment by garf** [comment]
Yes. You have to fork repository first to your account. Make changes there and then create full request from your fork to master of my repository.

**Comment by axelex** [comment]
I did that. How soon can someone have a look over the changes?

**Comment by garf** [comment]
@axelex I've made a new release so now you can publish config file and set your configuration file path there easily.

**Comment by axelex** [comment]
Thanks a lot @gaaarfild! 
I will look over it and see how it works.
